import type { Project } from "@/types/project";

export const projects = [
  {
    id: "Whats-app_appointment",
    name: "WhatsApp Appointment Booking",
    gitURL: "https://github.com/SAIKUMAR039/Whats-app_appointment",
    liveURL: "https://whats-app-appointment.vercel.app/",
    description:
      "A booking platform that helps businesses manage appointments through WhatsApp. The focus is on making the booking flow simple for both customers and staff.",
    technologies: ["React", "Next.js", "TypeScript", "Tailwind CSS"],
    image: "/projects/whatsapp-appointment.svg",
    year: "2025",
    features: [
      "Online appointment booking calendar",
      "Real-time schedule and slot management",
      "Responsive mobile-first user interface",
      "Clean modular application architecture",
      "Instant booking confirmation flows",
    ],
  },
  {
    id: "AI-Resume-Screening-System",
    name: "AI Resume Screening System",
    gitURL: "https://github.com/SAIKUMAR039/ai-resume-screening",
    liveURL: "https://ai-resume-screening-plum.vercel.app/",
    description:
      "A resume screening application that extracts candidate information and skills, then compares resumes with job descriptions using NLP. Built with Python, spaCy, FastAPI, React, and PostgreSQL.",
    technologies: [
      "Python",
      "spaCy",
      "FastAPI",
      "React",
      "PostgreSQL",
      "Tailwind CSS",
    ],
    image: "/projects/ai-resume-screening.png",
    year: "2026",
    features: [
      "Resume text parsing and structured data extraction",
      "Candidate-to-job keyword and skills matching",
      "Visual skills breakdown and ranking chart",
      "Recruiter review dashboard",
      "Fast asynchronous API endpoints",
    ],
  },
  {
    id: "Nerdy-AI-Studio",
    name: "Nerdy AI Studio",
    gitURL: "https://github.com/SAIKUMAR039/Nerdy",
    liveURL: "https://nerdyn.saikumarthota.live/",
    description:
      "A productivity web app with dedicated tools for code explanation, drafting, and writing assistance. Includes user authentication and session history tracking.",
    technologies: [
      "React",
      "TypeScript",
      "Vite",
      "Supabase",
      "Gemini API",
      "Tailwind CSS",
    ],
    image: "/projects/nerdy-ai-studio.png",
    year: "2025",
    features: [
      "Multi-purpose AI assistance tools",
      "Code explanation and syntax help",
      "Supabase authentication and user accounts",
      "Saved generation history",
      "Stripe payment integration",
    ],
  },
  {
    id: "Imagine",
    name: "Imagine AI Studio",
    gitURL: "https://github.com/SAIKUMAR039/Imagine",
    liveURL: "https://imagine.saikumarthota.live/",
    description:
      "An image generation tool that turns text prompts into custom visuals using generative AI. Features style presets, a personal gallery, and direct image downloads.",
    technologies: [
      "Next.js",
      "React",
      "TypeScript",
      "Gemini API",
      "Tailwind CSS",
    ],
    image: "/projects/imagine.png",
    year: "2024",
    features: [
      "Text-to-image prompt generation",
      "Preset style variation options",
      "Personal image gallery",
      "One-click file downloads",
      "Responsive layout for mobile and desktop",
    ],
  },
  {
    id: "IOT_parking_system",
    name: "IoT Smart Parking System",
    gitURL: "https://github.com/SAIKUMAR039/IOT_parking_system",
    liveURL: "https://github.com/SAIKUMAR039/IOT_parking_system",
    description:
      "A parking monitoring prototype that detects available spaces in real time using ultrasonic sensors and an Arduino board to help drivers find open spots.",
    technologies: ["Arduino", "C++", "IoT Sensors", "Embedded Systems"],
    image: "/projects/iot-parking.svg",
    year: "2025",
    features: [
      "Real-time parking space detection",
      "Ultrasonic sensor telemetry",
      "Automated status indicators",
      "Microcontroller-level control logic",
      "Low-power sensor operation",
    ],
  },
  {
    id: "File-Share",
    name: "File Share",
    gitURL: "https://github.com/SAIKUMAR039/FileShare",
    liveURL: "https://file-share.saikumarthota.live/",
    description:
      "A lightweight file-sharing tool for uploading documents and sharing them through secure, temporary links with live transfer status.",
    technologies: [
      "Next.js",
      "TypeScript",
      "React",
      "Firebase",
      "Tailwind CSS",
    ],
    image: "/projects/file-share.svg",
    year: "2024",
    features: [
      "Drag-and-drop file upload",
      "Unique shareable links",
      "Cloud storage integration",
      "Upload progress feedback",
      "Simple user account login",
    ],
  },
  {
    id: "Benege-AI-Chat",
    name: "Benege AI Chat",
    gitURL: "https://github.com/SAIKUMAR039/Benege",
    liveURL: "https://benege.vercel.app/",
    description:
      "A conversational interface that provides streaming AI replies, chat memory, and clean Markdown rendering for daily problem solving and research.",
    technologies: [
      "Next.js",
      "TypeScript",
      "React",
      "OpenAI API",
      "Tailwind CSS",
    ],
    image: "/projects/benege-ai-chat.svg",
    year: "2024",
    features: [
      "Streaming chat responses",
      "Contextual dialogue memory",
      "Conversation history view",
      "Clean Markdown output formatting",
      "Responsive dark theme",
    ],
  },
  {
    id: "Student-Utils",
    name: "Student Utils",
    gitURL: "https://github.com/SAIKUMAR039/ZedN",
    liveURL: "https://student-utils.vercel.app/",
    description:
      "A clean dashboard for students featuring a GPA calculator, quick notes, and an assignment deadline tracker in one place.",
    technologies: ["Next.js", "TypeScript", "React", "Tailwind CSS"],
    image: "/projects/student-utils.svg",
    year: "2024",
    features: [
      "Semester GPA and CGPA calculator",
      "Quick markdown note-taking",
      "Assignment deadline tracker",
      "Study timer",
      "Local storage data persistence",
    ],
  },
  {
    id: "Smart-Emergency-Alert-System",
    name: "Smart Emergency Alert System",
    gitURL: "https://github.com/SAIKUMAR039/Suraksha",
    liveURL: "https://air-tag-security.vercel.app/",
    description:
      "A personal safety web application designed to capture GPS coordinates and dispatch alert messages to emergency contacts with a single tap.",
    technologies: [
      "Next.js",
      "TypeScript",
      "React",
      "Node.js",
      "Tailwind CSS",
    ],
    image: "/projects/emergency-alert.svg",
    year: "2024",
    features: [
      "One-tap emergency trigger",
      "Live GPS coordinate capture",
      "Emergency contact notification list",
      "Mobile-friendly interface",
      "Low-bandwidth reliability",
    ],
  },
  {
    id: "ToDo-List",
    name: "Focus Task Manager",
    gitURL: "https://github.com/SAIKUMAR039/Todo-react-js",
    liveURL: "https://to-do-ract-js.vercel.app/",
    description:
      "A minimal task management app for organizing daily to-dos with priority tags, status filtering, and local browser storage persistence.",
    technologies: ["React", "JavaScript", "Tailwind CSS"],
    image: "/projects/todo-list.svg",
    year: "2024",
    features: [
      "Task entry and inline editing",
      "Category and priority filters",
      "Completion progress tracking",
      "Persistent browser storage",
      "Fast keyboard-friendly actions",
    ],
  },
  {
    id: "Weather",
    name: "Weather Radar",
    gitURL: "https://github.com/SAIKUMAR039/Weather",
    liveURL: "https://weather-sai.vercel.app/",
    description:
      "A responsive weather application providing current conditions, temperature forecasts, and wind data for cities worldwide using public weather APIs.",
    technologies: [
      "Next.js",
      "TypeScript",
      "React",
      "OpenWeather API",
    ],
    image: "/projects/weather.svg",
    year: "2024",
    features: [
      "Worldwide city weather search",
      "Current temperature and conditions",
      "5-day forecast cards",
      "Dynamic weather visuals",
      "Cached API requests",
    ],
  },
  {
    id: "Bitcoin-Price-Prediction",
    name: "Bitcoin Price Predictor",
    gitURL: "https://github.com/SAIKUMAR039/bit-coin-prediction-stramlit",
    liveURL: "https://coin-price-prediction.streamlit.app/",
    description:
      "A machine learning dashboard that analyzes historical cryptocurrency price trends and visualizes forecast models.",
    technologies: [
      "Python",
      "Streamlit",
      "Scikit-Learn",
      "Pandas",
    ],
    image: "/projects/bitcoin-prediction.svg",
    year: "2024",
    features: [
      "Historical price data ingestion",
      "Interactive trend charts",
      "Predictive machine learning models",
      "Date range selection",
      "Hosted on Streamlit Cloud",
    ],
  },
] as const;
